### ISSUE TITLE
Unable to build wallet from source on ubuntu 18

### ISSUE THREAD

**Issue by realsetvin** [PirateNetwork/pirate#100]
**Describe the bug**
fresh ubuntu install trying to build wallet from source but it hangs at 
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

found a similar issue https://github.com/bitcoin/bitcoin/issues/7970 but so far none of the solutions have worked for me. Some are beyond my head. Unsure how to proceed.

**Screenshots**
![image](https://github.com/PirateNetwork/pirate/assets/117243445/56f24568-498c-4957-aa0b-81d29953aa1b)

**Desktop (please complete the following information):**
ubuntu 18 vm

**Comment by TheComputerGenie** [comment]
Ubuntu 18 has reached its EOL.
