### ISSUE TITLE
zlib - curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by AlexSpain** [PirateNetwork/pirate#103]
Ubuntu 20.04

Build from source tar.gz  [Version 5.7.5 Signed Release](https://github.com/PirateNetwork/pirate/releases/tag/v5.7.5)

```
make: Entering directory '/node/pirate/pirate-5.7.5/depends'
mkdir -p /node/pirate/pirate-5.7.5/depends/sources/download-stamps /node/pirate/pirate-5.7.5/depends/sources
rm -f /node/pirate/pirate-5.7.5/depends/sources/download-stamps/.stamp_fetched-zlib-zlib-1.2.13.tar.gz.hash
touch /node/pirate/pirate-5.7.5/depends/sources/download-stamps/.stamp_fetched-zlib-zlib-1.2.13.tar.gz.hash
cd /node/pirate/pirate-5.7.5/depends/sources/download-stamps; (test -f /node/pirate/pirate-5.7.5/depends/sources/zlib-1.2.13.tar.gz || ( mkdir -p /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13 && echo Fetching zlib... && ( curl --location --fail --connect-timeout 10 --retry 3 -o "/node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/zlib-1.2.13.tar.gz.temp" "/zlib-1.2.13.tar.gz" || curl --location --fail --connect-timeout 10 --retry 3 -o "/node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/zlib-1.2.13.tar.gz.temp" "https://www.zlib.net/zlib-1.2.13.tar.gz" ) && echo "b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30  /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/zlib-1.2.13.tar.gz.temp" > /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/.zlib-1.2.13.tar.gz.hash && sha256sum -c /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/.zlib-1.2.13.tar.gz.hash && mv /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13/zlib-1.2.13.tar.gz.temp /node/pirate/pirate-5.7.5/depends/sources/zlib-1.2.13.tar.gz && rm -rf /node/pirate/pirate-5.7.5/depends/work/download/zlib-1.2.13 ))
Fetching zlib...
curl: (3) URL using bad/illegal format or missing URL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [funcs.mk:261: /node/pirate/pirate-5.7.5/depends/sources/download-stamps/.stamp_fetched-zlib-zlib-1.2.13.tar.gz.hash] Error 22
make: Leaving directory '/node/pirate/pirate-5.7.5/depends'

```

**Comment by AlexSpain** [comment]
need to change path at [depends/packages/zlib.mk](https://github.com/PirateNetwork/pirate/blob/77c6addf88080fe0717710f35ad24afcce596151/depends/packages/zlib.mk#L4)

from $(package)_download_path=https://www.zlib.net

to

$(package)_download_path=https://www.zlib.net/fossils

**Comment by blackmennewstyle** [comment]
I was about to post the same bug issue and the same fix, glad i took my time to read all the ones already opened lol

**Comment by CryptoForge** [comment]
The location of the file has changed. The new location has been updated on the master branch.

**Comment by TheComputerGenie** [comment]
> The location of the file has changed. The new location has been updated on the master branch.

The 404 error has nothing to do with the error in the title (there are 2 errors in the issue).
https://github.com/PirateNetwork/pirate/blob/bc59649d2d716f15e0795d4415b38b09f0aed3c9/depends/Makefile#L9 defines `FALLBACK_DOWNLOAD_PATH` (which is set to a non-reall URL) and https://github.com/PirateNetwork/pirate/blob/bc59649d2d716f15e0795d4415b38b09f0aed3c9/depends/funcs.mk#L25 attempts to use `PRIORITY_DOWNLOAD_PATH` (which is never set); *that* is the cause of the title error.

**Comment by CryptoForge** [comment]
Those 2 issues have been fixed and will be moved in to the master branch with the rest of dev-cpp17. 

https://github.com/PirateNetwork/pirate/commit/7ff0b340a54233586ea2626ff844a63222f89a9d

**Comment by AlexSpain** [comment]
Any reward for bug report from dev team? 
zs17tre8xs0984gyuyjgjjy3aqrgxl25esmctsujzmq9w805x8k725grwc8m8e4w5pr7yyqwdlg5x7

thank you

**Comment by CryptoForge** [comment]
The path to zlib issue was already known and patched twice before you reported it.

https://github.com/PirateNetwork/pirate/commit/77c6addf88080fe0717710f35ad24afcce596151

https://github.com/PirateNetwork/pirate/commit/882f152dbbe4b057dfd03768ad993e78466bc965

The 404 issue was resolved due to the code @TheComputerGenie pointed out.

**Comment by AlexSpain** [comment]
> The path to zlib issue was already known and patched twice before you reported it.
> 
> [77c6add](https://github.com/PirateNetwork/pirate/commit/77c6addf88080fe0717710f35ad24afcce596151)
> 
> [882f152](https://github.com/PirateNetwork/pirate/commit/882f152dbbe4b057dfd03768ad993e78466bc965)
> 
> The 404 issue was resolved due to the code @TheComputerGenie pointed out.

I was post fix before any others and bug. Other commit what you link not fix issue. thank you.
