### ISSUE TITLE
z_sendmany not usable

### ISSUE THREAD

**Issue by unek** [PirateNetwork/pirate#108]
**Describe the bug**
calling the `z_sendmany` RPC methods results in a `RPC Command disabled until witnesses are built.` error. 

this error is thrown [when `fInitWitnessesBuilt` is false](https://github.com/PirateNetwork/pirate/blob/master/src/rpc/server.cpp#L896-L897), but since 5.8.0, the variable [is never set to true](https://github.com/PirateNetwork/pirate/blame/master/src/wallet/wallet.cpp#L2599)

**To Reproduce**
1. use `z_sendmany` RPC method

**Comment by CryptoForge** [comment]
Thank you for alerting us. I'll fix this immediately.

**Comment by CryptoForge** [comment]
@unek I've fixed this with release v5.8.1
