### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheComputerGenie** [PirateNetwork/pirate#15]
New build options, new params, and new RPCs need documentation.

**Comment by TheComputerGenie** [comment]
https://github.com/PirateNetwork/pirate/actions/runs/459735339

**Comment by CryptoForge** [comment]
New build options and update file names have been documented in the REAME.md file. 

RPC documentation is part of a larger project wide initiative that is being implemented on the website. Currently all RPCs, including the new ones have documented usage by using the cli help command.
