### ISSUE TITLE
GUI crashes

### ISSUE THREAD

**Issue by TheComputerGenie** [PirateNetwork/pirate#16]
### Describe the issue
App crashes when attempting to sort by date a second time

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Click "Transactions"
2. Sort by date
3. Sort by date

### Expected behaviour
it should sort transactions by date in either direction

### Actual behaviour + errors
the entire app closess

### The version of Pirate you were using:
Pirate version v3.1.0-7dc670273

### Machine specs:
![image](https://user-images.githubusercontent.com/21057518/102602481-383bd380-40e7-11eb-93aa-76b5385cd9ea.png)

### Any extra information that might be useful in the debugging process.
debug.log shows:
`2020-12-18 10:06:24 GUI: ASSERT failure in QList<T>::operator[]: "index out of range", file /Users/cryptoforge/Dev/pirate/depends/x86_64-apple-darwin17.7.0/share/../include/QtCore/qlist.h, line 545`

**Comment by TheComputerGenie** [comment]
`2020-12-19 11:52:10 GUI: ASSERT failure in QList<T>::operator[]: "index out of range", file /home/cryptoforge/Dev/pirate_master/depends/x86_64-unknown-linux-gnu/share/../include/QtCore/qlist.h, line 545`
Seems to also happen in linux
Also of note there are blank spots in the transaction record 
![image](https://user-images.githubusercontent.com/21057518/102688852-3cd3bb00-41bf-11eb-8ad5-d02df863d578.png)

**Comment by TheComputerGenie** [comment]
![image](https://user-images.githubusercontent.com/21057518/102695986-a0c2a780-41f0-11eb-87dc-778d71068981.png)

**Comment by CryptoForge** [comment]
I've been able to reproduce the bug and have begun working on it.

**Comment by CryptoForge** [comment]
This issue should be resolved as of https://github.com/PirateNetwork/pirate/commit/b0dc825ef334be90be66ddb36980b51071eadc1d

**Comment by TheComputerGenie** [comment]
Seems good on linux, will build and check Mac tomorrow
