### ISSUE TITLE
`pirated` & `pirate-cli` scripts missing executable permission in Linux

### ISSUE THREAD

**Issue by himu007** [PirateNetwork/pirate#17]
### Describe the issue
The `pirated` & `pirate-cli` scripts doesn't run due to permission issue in Linux OS. They are not executable scripts due to missing permission.

### Can you reliably reproduce the issue?
Yes.
#### If so, please list the steps to reproduce below:
```
cd ~/pirate/src
./pirated
bash: ./pirated: Permission denied
```

### How to solve?
Issue `chmod +x pirated` & `chmod +x pirate-cli` from the `src` dir.

### Expected behaviour
When issuing `./pirated`, the chain should start and not throw permission denied error.

### The version of Komodo you were using:
`Komodo Daemon version v3.1.0-7dc670273

### Machine specs:
- OS name + version: Ubuntu 18.04

**Comment by CryptoForge** [comment]
These scripts will not be needed in the future as the daemon and cli file name will be changed to pirated and all of the command line arguments will be soft set of default to pirate.
