### ISSUE TITLE
Transaction record issue

### ISSUE THREAD

**Issue by TheComputerGenie** [PirateNetwork/pirate#18]
**Describe the bug**
Coinbase transactions in Transactions show as "Recieved from" miner's address

**To Reproduce**
1. Mine a block
2. Click on 'Transactions'

**Expected behavior**
Coinbase transactions in Transactions should show as "Mined" and the miner's address

**Screenshots**
![image](https://user-images.githubusercontent.com/21057518/102724035-1488b100-42d2-11eb-8216-42f04cf3b23a.png)

**Desktop (please complete the following information):**
 - OS: all
 - Version v3.1.0-d13f6f7ca

**Comment by CryptoForge** [comment]
This should be fixed as of https://github.com/PirateNetwork/pirate/commit/8f0ff6b721c2b8bb452125ff1125743467636a8c
