### ISSUE TITLE
sevenseas wallet sucks all machine resources

### ISSUE THREAD

**Issue by rickmts40** [PirateNetwork/pirate#19]
**Describe the bug**
sevenseas wallet when started will uses the entire ram available, cpu spikes to 90% 100% and the laptop freezes.

**To Reproduce**
1. start komodod daemon
2. start sevenseas wallet
3. memory ram start drain very quickly until computer becomes unresponsive.
4. logs says nothing out of normal.

**Expected behavior**
the wallet to work as any other wallet

**Screenshots**
no need.

**Desktop (please complete the following information):**
 - OS: linux Arch
 - Browser none
 - Version 

**Smartphone (please complete the following information):**
 - Device: none
 - OS: none
 - Browser none
 - Version none

**Additional context**
This is my first install, i am downloading the blockchain to an external drive, it already downloaded about 3% when the problem started to happen, rebooted Linux for the second time, also restarted wallet and komodo daemon.
In Arch qt5websockets is not installed by default with qt5 then i had to install it, besides that nothing was installed except the last release available of sevenseas.

**Comment by TheComputerGenie** [comment]
This is not the proper repository for that app.
