### ISSUE TITLE
Incorrect system date breaks wallet

### ISSUE THREAD

**Issue by jnhouse** [PirateNetwork/pirate#22]
**Describe the bug**
Having incorrectly set the system date a year ahead of time, the chain sync is broken and there are problems with the wallet.dat

**To Reproduce**
A few days ago around December 29th, I set the time to 2021-12-29 then opened komodo-qt.  I did this because the system time was behind due to being in sleep mode.

**Expected behavior**
The chain should sync

**Screenshots**

**Desktop (please complete the following information):**
WSL Ubuntu 20.04
komodo-qt v3.1.0-7dc670273

**Additional context**
After fixing the date and relaunching the application, I can't remember what happened, but the chain state was broken.  Originally I tried to resync the chain several times and got a segmentation fault a few weeks before the the last block.

Next I started a new ~/.komodo/PIRATE folder with an older wallet backup and it syncs properly, but when I use my newest wallet (that was not backed up before setting the system time incorrectly), which has an additional receiving address in it, I get more error messages and the chain won't sync.  The console gives me this message:

`EXCEPTION: St13runtime_error       
CDB: Error -30972, can't open database        
Komodo in ProcessMessages() `

However, I can see the two receiving addresses in the receive menu and the application does not exit.  I went back to syncing with the old wallet.  I then opened the application back up with my newest wallet and this happened:

`EXCEPTION: St13runtime_error       
CWalletDB::ListAccountCreditDebit(): cannot create DB cursor       
Komodo in Runaway exception       

komodo-qt: /root/pirate/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion !posix::pthread_mutex_destroy(&internal_mutex)' failed.
Aborted`

Please help me, as I do have a transaction with the newer address!  I've noticed the wallet size of my original was 92K and when I backed up the current wallet it was 80K.  After syncing the chain my (older) wallet was about 209K.  Is my newest wallet recoverable?

**Comment by kaks25** [comment]
@jnhouse try these troubleshoot
- Close the wallet make sure you are using the latest wallet https://github.com/PirateNetwork/pirate/releases/download/v3.1.1/pirate-qt-ubuntu1804-v3.1.1.zip
- Delete the previous (Blocks and Chainstate) folders from (~/.komodo/PIRATE/) Directory, Download and extract the bootstrap file on PIRATE folder 
Bootstrap link : https://eu.bootstrap.dexstats.info/ARRR-bootstrap.tar.gz
- launch the wallet

If it doesn't work:
- Rename wallet.dat file to wallet-old.dat
- import the privatekey

How to import the private key?
launch pirateocean > Click on help >  debug window > console then type
z_importkey `Replacewithyourprivatekey` yes

**Comment by CryptoForge** [comment]
Use v3.1.1 with the bootstrap=1 option in your PIRATE.conf file. This will completely reset your block, chainstate and transactions.

**Comment by jnhouse** [comment]
Thank you both very much!  It works again and didn't need to import private key.
