### ISSUE TITLE
getblocktemplate close the node without errors in debug.log

### ISSUE THREAD

**Issue by solopool** [PirateNetwork/pirate#25]
Hello!

If we run node with options:
```
mineraddress=OURADDRESS
disablewallet=1
minetolocalwallet=0
```

After full synchronization rpc command "getinfo" works fine. But rpc command "getblocktemplate" close the node without errors in debug.log.

**Comment by TheComputerGenie** [comment]
https://github.com/KomodoPlatform/komodo/pull/399
looks like it would fix this
@CryptoForge

**Comment by solopool** [comment]
> [KomodoPlatform#399](https://github.com/KomodoPlatform/komodo/pull/399)
> looks like it would fix this
> @CryptoForge

It's works fine for Komodo, but for Pirate partially solves issue. Node often closes without error. It's random.

**Comment by CryptoForge** [comment]
@solopool is you node closing without error on just this RPC call?

**Comment by CryptoForge** [comment]
I pulled in this fix here.
https://github.com/PirateNetwork/pirate/commit/5261bc7ec57fa2da2da91d31eac0961f50fac5d4
