### ISSUE TITLE
Implement offline transaction signing

### ISSUE THREAD

**Issue by crocket** [PirateNetwork/pirate#26]
It would increase security greatly.

**Comment by mullroy** [comment]
Please visit https://github.com/mullroy/pirate_offline for a Pirate treasure chest wallet with offline transaction signing
capability. The offline transaction signing is currently only accessible via the debug console, with two new commands
added: 'z_sendmany_prepare_offline' and 'z_sign_offline'.
Instructions on how to use the commands are contained in the file: README_offline_transaction_signing.md

If you find the feature useful, please consider a donation on the PIRATE network to: 
  zs1r48kgx3rmp60lx5v38dxaurx6ds8w832qrw5j07kact4zfuw5gmkpvpejx64etzxg4s5c90r7jl

**Comment by mullroy** [comment]
Please visit https://github.com/mullroy/pirate_offline for a Pirate treasure chest wallet with offline transaction signing capability. The functionality is now added to the Qt GUI.

To run the wallet in on-line mode: set maxconnections=100 in PIRATE.conf (or any number larger than 0). To run the wallet in off-line mode: set maxconnections=0
On the off-line wallet you do not need the ~9GB of blockchain data. You do however need the .zcash-parameters of approx 1.5GB.

**Comment by crocket** [comment]
Closing this because it was implemented?
