### ISSUE TITLE
Issue with compiling in Manjrao linux

### ISSUE THREAD

**Issue by bienenboris** [PirateNetwork/pirate#29]
### Helllooouuuu, 

even though the Software seems to be intended for Ubuntu based / Debian OS, I tried to compile the thang. 
I didn't succeed. _IF_ you gallant guys feel compelled to support a solution for Arch linux and Manjaroa as well _(I am in Plasma / KDE environment, thus QT libs are there)_ I have my issue here. 

It is to note that:

- I used the following command to compile 
 #For qt GUI binaries
./zcutil/build-qt-win.sh -j8
- _libc6-dev m4 g++-multilib libncurses-dev_ are not available in the pacman Arch tree. 

AFAIK there is no easy-to-use wallet for ARRR available at present, due to **way-to-long sync times** with the classic ARRR wallet _that you could put on your USB stick_.

Thanks a lot! <3
B

PS: 
Now here is the first output I could get from konsole:

`[...]
/usr/share/pirate/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -o libsnark/gadgetlib1/constraint_profiling.o   libsnark/gadgetlib1/constraint_profiling.cpp -c -MMD  -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE  -fPIC -DBINARY_OUTPUT -DNO_PT_COMPRESSION=1 -fstack-protector-all -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-comment -Wfatal-errors -O2 -march=x86-64 -DMONTGOMERY_OUTPUT -DCURVE_ALT_BN128 -I/usr/share/pirate/depends/x86_64-unknown-linux-gnu/share/../include -Ilibsnark -DNO_PROCPS -static -DSTATIC -DMULTICORE -fopenmp
mv -f .deps/libbitcoin_util_a-util.Tpo .deps/libbitcoin_util_a-util.Po
ar q libsnark.a libsnark/algebra/curves/alt_bn128/alt_bn128_g1.o libsnark/algebra/curves/alt_bn128/alt_bn128_g2.o libsnark/algebra/curves/alt_bn128/alt_bn128_init.o libsnark/algebra/curves/alt_bn128/alt_bn128_pairing.o libsnark/algebra/curves/alt_bn128/alt_bn128_pp.o libsnark/common/profiling.o libsnark/common/utils.o libsnark/gadgetlib1/constraint_profiling.o
ar: création de libsnark.a
if [ -n "" ]; then mkdir -p tmp-ar; cd tmp-ar; for AR_LIB in ; do ar x $AR_LIB; done; ar qc libsnark.a tmp-ar/*; cd ..; rm -r tmp-ar; fi;
ar s libsnark.a
make[3]: Verzeichnis „/usr/share/pirate/src/snark“ wird verlassen
cc1plus: Warnung: Kommandozeilenoption »-Wint-conversion« ist gültig für C/ObjC, aber nicht für C++
mv -f crypto/.deps/libverus_crypto_a-verus_clhash.Tpo crypto/.deps/libverus_crypto_a-verus_clhash.Po
cc1plus: Warnung: Kommandozeilenoption »-Wint-conversion« ist gültig für C/ObjC, aber nicht für C++
mv -f crypto/.deps/libverus_portable_crypto_a-verus_clhash_portable.Tpo crypto/.deps/libverus_portable_crypto_a-verus_clhash_portable.Po
mv -f zcash/address/.deps/libzcash_a-zip32.Tpo zcash/address/.deps/libzcash_a-zip32.Po
make[2]: Verzeichnis „/usr/share/pirate/src“ wird verlassen
make[1]: *** [Makefile:8684: all-recursive] Fehler 1
make[1]: Verzeichnis „/usr/share/pirate/src“ wird verlassen
make: *** [Makefile:712: all-recursive] Fehler 1
[powerhost pirate]# 
`

**Comment by CryptoForge** [comment]
The full node is now buildable on Manjaro

**Comment by CryptoForge** [comment]
Using these packages will allow you to build the node on the most recent release of manjaro.

base-devel pkg-config glibc m4 gcc autoconf libtool ncurses unzip git python python-pyzmq zlib wget libcurl-gnutls automak
e curl cmake mingw-w64
