### ISSUE TITLE
Add torv3 support

### ISSUE THREAD

**Issue by nolim1t** [PirateNetwork/pirate#32]
**Is your feature request related to a problem? Please describe.**
This isn't an issue yet, but for the longevity of this project torv3 should be support.

Please see the [deprecation schedule](https://blog.torproject.org/v2-deprecation-timeline)

**Describe the solution you'd like**

Similar to what the bitcoin core team has done with their v0.21.0 client. It seems protocol involved too. Can probably take a try at the changes too when I have some time.

**Describe alternatives you've considered**
No alternative other than not using tor.

**Comment by CryptoForge** [comment]
TorV3 functionality is now part of the code base as of version 5.6.0
