### ISSUE TITLE
Never ending "connecting to peers"

### ISSUE THREAD

**Issue by achalendar** [PirateNetwork/pirate#35]
Dear all, 
I am excited to make my first post on this forum.

I downloaded the app for my mac Treasure Chest, and it seems to never properly sync with the network (already 24hours and nothing happening). I sent a couple of ARRRs from Tradeogre to Treasurechest to see if it worked, and obviously, it doesn't. 

Is this normal? Is there something I can do to fix it?

OS: iOS on big sur
<img width="989" alt="Screenshot 2021-04-22 at 20 49 19" src="https://user-images.githubusercontent.com/83034432/115769808-427b2080-a3ac-11eb-8ed1-0a8434201d67.png">

Thanks a lot for your help in advance,
Aurélien

**Comment by exilnur** [comment]
Currently I also have this problem on Ubuntu, so this issue is not isolated to Mac.

**Comment by kaks25** [comment]
You need to add ip nodes:
click on  Settings > Options > Open Configuration File 

then type
addnode=78.63.47.105
addnode=46.4.67.239
addnode=139.99.145.129
addnode=94.130.32.156
addnode=173.212.200.221
addnode=66.248.204.186
addnode=91.206.15.138
addnode=217.69.15.197
addnode=38.91.101.236
addnode=49.12.83.114
addnode=158.69.26.155
addnode=51.81.56.52
addnode=84.38.184.139

Save the PIRATE.conf file and restart the treasure chest

**Comment by CryptoForge** [comment]
peers updated in the latest version.

https://github.com/PirateNetwork/pirate/commit/1b2234da783e4c7ac369e06ae39e1c4478e3f2d6
