### ISSUE TITLE
I can't uninstall Pirate chain Wallet under Ubuntu

### ISSUE THREAD

**Issue by Edi456** [PirateNetwork/pirate#36]
I've Installed the full node wallet of Pirate chain whit those commands but now it's impossible to uninstall (and there is no indication nowhere : 
chmod + pirate-qt-linux
./pirate-qt-linux

There is no icon in the menu and I don't find neither anything in the synaptic package manager to uninstall. I have a folder .komodo of 10 GB in my Home folder an another one of .zcash-params.

I'd like to make a complete uninstalling without letting configuration files.

Can you indicate me how to proceed ?

Thanks.

**Comment by TheComputerGenie** [comment]
Simply find `pirate-qt-linux` and delete it. There's no "uninstall" because it's a single file and there's no "install".
