### ISSUE TITLE
Transactions view Date column when tx was downloaded rather than recorded

### ISSUE THREAD

**Issue by AArnott** [PirateNetwork/pirate#37]
**Describe the bug**

The Treasure Chest displays its list of transactions with a date column populated with the time each tx was downloaded rather than when it was broadcast or recorded. 

**To Reproduce**

1. Start TC for the first time on a computer.
2. Import an existing key for an address that already has transactions on it.
3. View Transactions in TC.
4. Observe the Date on all transactions indicate they all happened at the same time (just now).

**Expected behavior**

I expect each transaction date to represent when it occurred, rather than when it was downloaded by this wallet app.

**Screenshots**

![image](https://user-images.githubusercontent.com/3548/117164254-aecd2b00-ad81-11eb-9275-0e6fc3dbade6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Pirate version v5.0.0-a0f518dfd (64-bit)

**Comment by kaks25** [comment]
Its a wallet feature when the deletetx and consolidation are enabled, so nothing to worry about.

**Comment by CryptoForge** [comment]
This commit should fix this issue.
https://github.com/PirateNetwork/pirate/commit/4bdf8fdad78d8bce29855b4c0c9308f5c227944f
