### ISSUE TITLE
can not receive ARRR

### ISSUE THREAD

**Issue by kiewahhau** [PirateNetwork/pirate#38]
On 5 May at 09:29 I have deposited 50 ARRR to this address: zs1vdawfnfhfll3843clpxk6t39g7x68edtyer53llkr3pzkuy9a63pp0n7z3mgaeqdrxky7unz8zs
But still I have not received 50 ARRR at my Tradegore account. Please contact me with my e-mailadres: kiewahhau@gmail.com

**Comment by TheComputerGenie** [comment]
You need to contact the exchange.
