### ISSUE TITLE
Didnt receive Pirate chain

### ISSUE THREAD

**Issue by noel9127** [PirateNetwork/pirate#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I didnt receive pirate chain i sent to tradeorge i see that its down for maintenance how long will it take ?

**Comment by TheComputerGenie** [comment]
You need to contact the exchange, this has nothing to do with the wallet or the chain.
