### ISSUE TITLE
DEX (CoinEx and TradeOgre) Deposits/Withdrawals issues

### ISSUE THREAD

**Issue by fabiobfava** [PirateNetwork/pirate#41]
Yay mates! We're having both CoinEx and now TradeOgre making ARRR deposits/withdrawals unavailable. Is there any prediction to have it possible? Both say we should contact you folks. I'm currently not making any trade on ARRR (and the moment is great to get ARRR). Sorry for disturbing, hope it can happen soon, cheers!

**Comment by TheComputerGenie** [comment]
You need to contact the exchange, this has nothing to do with the wallet or the chain.

**Comment by fabiobfava** [comment]
So Pirate Chain confirms that there's not an upgrade being rolled-out? Also no problems on the network? Any DEX where it could be working now? Thanks, cheers!

**Comment by TheComputerGenie** [comment]
There are always updates being done by Forge.
The point is that any issue you are having with an exchange is an issue with that exchange, not the network or the chain or actual transaction functionality.
What exchange does what is a 3rd party thing and not related to the core project or the actual chain.

**Comment by TheComputerGenie** [comment]
There are always updates being done by Forge.
The point is that any issue you are having with an exchange is an issue with that exchange, not the network or the chain or actual transaction functionality.
What exchange does what is a 3rd party thing and not related to the core project or the actual chain.

**Comment by jcalfee** [comment]
I recently got a reply from CoinEx:
```
The exact time is unknown yet. It depends on wallet maintenance progress. 

Due to the network upgrade of ARRR, CoinEx has suspended ARRR deposit and withdrawal to ensure our users' assets security. The details are as follows. 

ARRR Deposit and Withdrawal:
Close on: March 22, 2021 (UTC)
Estimated time to reopen: Depends on the update progress.

If you are in a hurry, you may exchange ARRR into BTC/USDT and withdraw BTC/ USDT instead.
```
Although they don't say what network, the opening phrase leaves one open to wonder: `Due to the network upgrade of ARRR.` ..

**Comment by fabiobfava** [comment]
Hey there, 

Thank you for the infos. I believe in Pirate Chain, so I prefer to keep them.

Please, as possible keep customers informed when we can withdraw ARRR.

Thank you very much for understanding and helping us out.

Cheers,

___________________________________________

Fabio Fava - https://fabiofava.com - ***@***.***
