### ISSUE TITLE
waiting for transfer from wallet to exchange over 2.5 hrs

### ISSUE THREAD

**Issue by krisg-sketch** [PirateNetwork/pirate#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheComputerGenie** [comment]
You need to contact the exchange and have them get their end working properly; despite what they wrote, this has nothing to do with the wallet or the chain.
