### ISSUE TITLE
maintenance going on for ages

### ISSUE THREAD

**Issue by gerttait** [PirateNetwork/pirate#49]
account maintenance is going on for ages and when `i want to use Tradeogre it just say 'maintenance'.
this is important to be able to trade crypto currencies at crucial times, hence these maintenances for ages is restricting the way we can use Tradeogre and force us to look into alternative exchanges
please sort it out!

**Comment by TheComputerGenie** [comment]
You need to contact the exchange and have them get their end working properly; despite what they wrote, this has nothing to do with the wallet or the chain.
