### ISSUE TITLE
Deposit to TradeOgre from Wallet Lite

### ISSUE THREAD

**Issue by krazeelegz** [PirateNetwork/pirate#50]
Deposited my lite wallet balance to TradeOgre (TO) this morning to do some day trading. Been a couple hours and still not showing in TO. When I went back to check the deposit page on TO, I noticed the warning (attached), and the suggestions to "Submit an issue to Pirate developers for faster load times". I am therefor doing so. Thanks.

<img width="1163" alt="Screen Shot 2021-05-10 at 10 48 14 AM" src="https://user-images.githubusercontent.com/8739982/117702864-eec75000-b17d-11eb-9dc9-4e202b37ef0c.png">

**Comment by TheComputerGenie** [comment]
You need to contact the exchange and have them get their end working properly; despite what they wrote, this has nothing to do with the wallet or the chain.
