### ISSUE TITLE
Wallet not active on tradeogre

### ISSUE THREAD

**Issue by garington** [PirateNetwork/pirate#51]
**Describe the bug**
Pirate chain wallet not active on trade ogre

**To Reproduce**
 Try to send from pirate chain wallet to tradeogre

**Expected behavior**
Wallet should have been operation and provided an address to send to from wallet app

**Screenshots**
'Warning: Pirate Chain wallet software is unable to cope with demands of exchange, because of these inefficiencies your deposit will take several hours to process and appear. Submit an issue to Pirate developers for faster load times.' 

**Smartphone (please complete the following information):**
 - Device: [huawei p30 pro]
 - OS: [11.0.0]
 - Browser [firefox]
 - Version [88.1.3 (Build #2015808507)
AC: 74.0.13, ccf500706
GV: 88.0.1-20210504152106
AS: 74.0.1]

**Additional context**

**Comment by TheComputerGenie** [comment]
You need to contact the exchange and have them get their end working properly; despite what they wrote, this has nothing to do with the wallet or the chain.
