### ISSUE TITLE
Tradeoger funds stuck

### ISSUE THREAD

**Issue by DKirchp** [PirateNetwork/pirate#52]
I have some ARRR stuck on tradeoger. Wallet was not even showing up. Before it said under maintenance. Did my trade already just want to withdraw funds. "Warning! This wallet is currently not online, so withdrawals will not work."  First time using Tradeoger.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheComputerGenie** [comment]
You need to contact the exchange and have them get their end working properly; despite what they wrote, this has nothing to do with the wallet or the chain.
