### ISSUE TITLE
Mac brew bundle adds gcc@6, build needs gcc@8

### ISSUE THREAD

**Issue by brianmcfadden** [PirateNetwork/pirate#55]
**Describe the bug**
The README-mac.md and the Brewfile will use gcc@6, but the build requires gcc@8

**To Reproduce**
Build without gcc@8 installed.  The build will fail:
configure: error: C++ compiler cannot create executables

**Expected behavior**
The build should begin.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Additional context**
Configure checks for g++-8.  This is from the config.log:

configure:4526: checking whether the C++ compiler works
configure:4548: g++-8 -pipe -O1 -arch x86_64 -I/usr/local/Cellar/gcc\@8/8.3.0/include/c++/8.3.0/ -I$PREFIX/include -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -Werror -g -Wl,-undefined -Wl,dynamic_lookup -I/Users/brian/Projects/pirate/depends/x86_64-apple-darwin19.6.0/share/../include/ -I/Users/brian/Projects/pirate/depends/x86_64-apple-darwin19.6.0/include -arch x86_64 -L/Users/brian/Projects/pirate/depends/x86_64-apple-darwin19.6.0/share/../lib -L/Users/brian/Projects/pirate/depends/x86_64-apple-darwin19.6.0/lib -arch x86_64 -Wl,-no_pie conftest.cpp  >&5
./configure: line 4550: g++-8: command not found
configure:4552: $? = 127
configure:4592: result: no

**Comment by CryptoForge** [comment]
I updated all the gcc@6 references to gcc@8

https://github.com/PirateNetwork/pirate/commit/7d7e20e42e121552cec3e0a4e60346fce0817f31
