### ISSUE TITLE
libgmp issue when building on Mac

### ISSUE THREAD

**Issue by brianmcfadden** [PirateNetwork/pirate#57]
**Describe the bug**
I'm trying to build for macos, and I'm getting an error:
configure:31933: error: libgmp missing

**To Reproduce**
Follow the directions in README-mac.md, up until the point where it says to run:
./zcutil/build-mac.sh

**Expected behavior**
The build should complete without error.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Additional context**
So, while it says that gmp is missing, it's actually not.  The error is happening during a configure, specifically:
configure:31895: checking for __gmpn_sub_n in -lgmp

However, that symbol exists in the libgmp.dylib, so that's not the problem.  The problem seems to be this, which was pulled from the config.log:

conftest.cpp:64:18: error: structured bindings only available with -std=c++17 or -std=gnu++17 [-Werror]
   extern "C" int [__gmpn_sub_n] ();
                  ^
conftest.cpp:64:18: error: structured binding declaration cannot have type 'int'
   extern "C" int [__gmpn_sub_n] ();
                  ^~~~~~~~~~~~~~

**Comment by volbil** [comment]
Hey, I encountered same issue recently, have you figure it out?

**Comment by brianmcfadden** [comment]
Commit 0d4858994f4b0e1f18f6a830b335376f051830e1 from ca333@keemail.me seems like the explicit fix for this issue. That commit builds fine for me. In fact, everything builds fine up to and including 22035cca956a35d9fe2be8df07713f2fc5a272dc; but, the commit right after that is "Merge remote-tracking branch 'komodo/dev' into pirate_da_dev", which is commit 68e4a6691249b7a41482ed55b37301edc210f8ea, and that merge seems to introduce another problem, multiple definitions for PACKAGE_BUGREPORT, PACKAGE_NAME, and others. So the HEAD of master doesn't work, either, but for different reasons.

If 0d485 builds for you, then I think we can close this issue.

**Comment by CryptoForge** [comment]
@brianmcfadden So you no longer have this issue on the master branch?

**Comment by brianmcfadden** [comment]
./zcutil/build-mac.sh appears to complete succesfully after commit 0d4858994f4b0e1f18f6a830b335376f051830e1, so this issue seems to have been taken care of.  I still can't make a complete build, but it has nothing to do with libgmp.
