### ISSUE TITLE
ARRR configuration

### ISSUE THREAD

**Issue by Wangmmx** [PirateNetwork/pirate#59]
Is the configuration of ARRR the same as that of komodo? pubKeyHash is 0x3c, scriptHash is 0x55, wif is 0xbc

**Comment by TheComputerGenie** [comment]
Yes, the transparent addresses (used only for block creation and notarizations) use the same bits as KMD
https://github.com/PirateNetwork/pirate/blob/master/src/chainparams.cpp#L188-L192

**Comment by Wangmmx** [comment]
Thank you for your reply!
btw, this kind of transparent address cannot send transactions, right? It seems that the z address can only send transactions? But I can see transactions of this kind of address on the browser:
http://pirate.explorer.dexstats.info/tx/aa1f23862395bf3e7d69e12a7259f058ac34dfa695b3762406ac3154d73a030c

**Comment by TheComputerGenie** [comment]
That transaction is one of the 2 rule exceptions, it is a "notarization" transaction which carries checkpoint data in the `OP_RETURN`

**Comment by Wangmmx** [comment]
Oh it means this is not a normal transfer transaction, is it?

I am generating a KMD format address, so I still need to generate a z address to verify the transfer operation, how do I generate a z address from a KMD address? 

Also, is there an external node that can be used? If not, I will set up my own node now. 

I am doing the support of the exchange, so I may ask more. Thank you for your patient answer.

**Comment by TheComputerGenie** [comment]
> it means this is not a normal transfer transaction, is it?

correct, it is a specialized transaction for notarization  
> how do I generate a z address from a KMD address?

You don't, there is no correlation between transparent addresses and private
`z_getnewaddress` creates a new z/private address
> is there an external node that can be used? If not, I will set up my own node now.

I'm not following what you mean by "external node"; it's a P2P network just like any other chain
> I am doing the support of the exchange

What exchange?

**Comment by Wangmmx** [comment]
> You don't, there is no correlation between transparent addresses and private
> `z_getnewaddress` creates a new z/private address

Is there any offline function to create a new z address? I need the offline api

> I'm not following what you mean by "external node"; it's a P2P network just like any other chain


Sorry for my bad expression,  I mean that I don’t need to set up a node by yourself, I can use a public RPC node to call the api interface.


> What exchange?

Is this important? Sorry i'm inconvenient to say


Thanks for your reply again
