### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Oink70** [PirateNetwork/pirate#60]
**Describe the bug**

On aarch64 binaries, the daemon version shows `"KMDversion": "0.6.1"`, while the downloaded binary version is `pirate-cli-aarch64-v5.0.0.zip`. This makes it impossible for automated checking if a system is running the latest released version.

**To Reproduce**
1. install `pirate-cli-aarch64-v5.0.0.zip` on an ARM device
2. start `pirated`
3. wait for it to connect to peers
4. run `pirate-cli getinfo`

**Expected behavior**
I expect it to show the same release version (preferably `"PIRATEversion": "5.0.0"`), to be able to automate checking.

**Comment by TheComputerGenie** [comment]
`KMDversion` represents the version the Pirate source code is synced with.
Unlike some SCs, PIRATE is still in sync with komodo source.
As long as PIRATE is in sync with KMD source, it will always display the `KMDversion`.

**Comment by CryptoForge** [comment]
The new version will include a PIRATEversion in the getinfo rpc.

https://github.com/PirateNetwork/pirate/commit/e81e9c47edf40cf5e57c838d4baa00ca62ef7c34
