### ISSUE TITLE
RC version not released as pre-release

### ISSUE THREAD

**Issue by Oink70** [PirateNetwork/pirate#61]
**Is your feature request related to a problem? Please describe.**
5.1.0-rc1 source code is released as production release (without binaries), while the name suggests it is a Release Candidate. Automated checks report that my local running daemon is not the same as the released ones on Github.

**Describe the solution you'd like**
Use the flag `"prerelease": true` to properly represent the status of the release.

**Comment by CryptoForge** [comment]
tag set to prerelease
