### ISSUE TITLE
The explorer cannot find the z-address

### ISSUE THREAD

**Issue by Wangmmx** [PirateNetwork/pirate#62]
At present, only transparent addresses are displayed, and I can’t find z-address when I search. Will the explorer be modified later? 

And I found the offline functions to create z-address, I don’t understand how to generate the private key. Previously, it was a transparent address generated according to the kmd configuration. Now the private key is not clear. The address prefix is zs, and it encoded as the bech32. I need to look for relevant information carefully.

No other meaning, I still want to thank you, sorry that the previous conversation was very unpleasant

**Comment by TheComputerGenie** [comment]
> Will the explorer be modified later?

No, because that's the point, the explorer will never have z information because it cannot be seen by anyone not having a key involved in the transaction (aka: privacy)

As for the key bit, I keep trying to explain to you that it's not the same creature:
![image](https://user-images.githubusercontent.com/21057518/118798208-ff08ba80-b862-11eb-97a0-7feb94461eeb.png)

**Comment by Wangmmx** [comment]
> No, because that's the point, the explorer will never have z information because it cannot be seen by anyone not having a key involved in the transaction (aka: privacy)

Can't find the z information with the rpc interface?

> As for the key bit, I keep trying to explain to you that it's not the same creature:

Where can I see similar key information in this picture


Thanks a lot

**Comment by TheComputerGenie** [comment]
https://zips.z.cash/protocol/protocol.pdf#addressesandkeys

**Comment by Wangmmx** [comment]
so even if I use the RPC request, I can’t get the balance of other people’s addresses or transactions, right?

**Comment by TheComputerGenie** [comment]
> so even if I use the RPC request, I can’t get the balance of other people’s addresses or transactions, right?

correct

**Comment by Wangmmx** [comment]
Okay, I get it. It sounds a bit difficult to develop. I have developed and supported BTC and ZEC, I thought it was similar, but ARRR looks very different, thanks again , and close this issue
