### ISSUE TITLE
The pirate-qt-ubuntu1804-v5.1.1-1.deb installer includeds "piratewallet-lite.desktop" filename

### ISSUE THREAD

**Issue by janos-r** [PirateNetwork/pirate#65]
**Describe the bug**
The pirate-qt-ubuntu1804-v5.1.1-1.deb installer includeds "piratewallet-lite.desktop" filename.
So this breaks if lite-wallet is already installed. Also, this is definitely unintended.

**To Reproduce**
Download the current "pirate-qt-ubuntu1804-v5.1.1-1.deb" from the releases.
Try to install it on an ubuntu based system.

**Expected behavior**
To install the correct .desktop file.

**Comment by CryptoForge** [comment]
I fixed the filename and updated the released files.

https://github.com/PirateNetwork/pirate/commit/9ee3faa62f4894480666bf672dd0674f8cf66842
