### ISSUE TITLE
Error Error compiling qt GUI binaries for arch linux

### ISSUE THREAD

**Issue by acul71** [PirateNetwork/pirate#70]
**Describe the bug**
Error compiling qt GUI binaries version v5.2.0-cee47a746-dirty (64-bit) for arch linux

```bash
qtbase/src/corelib/tools/qbytearraymatcher.h: 
error: 'numeric_limits' is not a member of 'std'
g++ --version
g++ (GCC) 11.1.0
```

**To Reproduce**
```bash
./zcutil/build-qt-linux.sh -j8
```

**Additional context**.
fixed adding:
```c
#include <stdexcept>
#include <limits>
```
in file: 
```bash
qtbase/src/corelib/tools/qbytearraymatcher.h
```

**Comment by kn0wmad** [comment]
Can confirm this also fixed my Arch build woes.  Thanks @acul71

**Comment by joickle** [comment]
I also had the same error on Manjaro, big thanks for the quick fix @acul71 :)

**Comment by joickle** [comment]
New AUR package for Arch users: https://aur.archlinux.org/packages/treasure-chest-bin
