### ISSUE TITLE
Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by joickle** [PirateNetwork/pirate#82]
Hey Guys,

After several hours of trial and error, I have a working PKGBUILD for Arch Linux to build pirate-qt from source using Arch system libraries. A few files need to be patched for it to build successfully, which I assume is due to newer libraries in Arch.

They can be obtained here or by using your favorite AUR helper: 

https://aur.archlinux.org/packages/pirate-qt
https://aur.archlinux.org/packages/pirate-cli

I will be keeping these updated with the latest releases going forward. 

EDIT: Added cli pkgbuild

**Comment by TheComputerGenie** [comment]
Why not make a PR to add the changes?

**Comment by joickle** [comment]
I can do a PR to add the changes, but the purpose of this was the PKGBUILD to make it easy for Arch users to build a package to install on Arch based distro's as you only provide packages for Ubuntu on Linux. 

Even after the patch is no longer needed and removed, the PKGBUILD is useful for Arch as it takes care of all the dependencies, etc. ;)
